/**
 * Generate Material 3 colour role tokens from a single source colour.
 *
 *   node scripts/gen-theme.mjs
 *
 * M3 does not use hand-picked hex values. A source colour is converted to HCT
 * (hue / chroma / tone), five tonal palettes are derived from it, and 13 tones
 * of each are mapped onto semantic ROLES (primary, on-primary, surface-
 * container-high, ...). Light and dark schemes come from the same palettes at
 * different tones, which is why M3 dark mode looks deliberate rather than
 * inverted.
 *
 * Run at build time, output committed, so the app ships static CSS with no
 * runtime colour maths and no dependency in the container.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  argbFromHex,
  hexFromArgb,
  themeFromSourceColor,
} from "@material/material-color-utilities";

// Sky blue — the accent the app already used. Everything else is derived.
const SOURCE = "#0284c7";

// The navy chrome is NOT derived. Authentic M3 navigation drawers are light
// surfaces; keeping navy is a deliberate, documented departure to preserve the
// app's identity (see HANDOFF). Treated as a fixed brand surface with its own
// on-colours, chosen for contrast rather than generated.
const NAV = {
  "nav-surface": "#071626",
  "nav-surface-container": "#0e2740",
  "nav-on-surface": "#dbe6f2",
  "nav-on-surface-variant": "#9db3c9",
  "nav-outline": "rgba(255, 255, 255, 0.10)",
};

const theme = themeFromSourceColor(argbFromHex(SOURCE));

/** The role tokens we actually consume. M3 defines more; unused ones are noise. */
const ROLES = [
  "primary",
  "onPrimary",
  "primaryContainer",
  "onPrimaryContainer",
  "secondary",
  "onSecondary",
  "secondaryContainer",
  "onSecondaryContainer",
  "tertiary",
  "onTertiary",
  "tertiaryContainer",
  "onTertiaryContainer",
  "error",
  "onError",
  "errorContainer",
  "onErrorContainer",
  "background",
  "onBackground",
  "surface",
  "onSurface",
  "surfaceVariant",
  "onSurfaceVariant",
  "outline",
  "outlineVariant",
  "shadow",
  "scrim",
  "inverseSurface",
  "inverseOnSurface",
];

const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/**
 * Surface containers are the five elevation-ish surface tones M3 uses instead
 * of stacking shadows. material-color-utilities exposes the neutral palette,
 * so we read the tones the spec assigns to each container level.
 */
function surfaceContainers(palettes, dark) {
  const n = palettes.neutral;
  const tone = (t) => hexFromArgb(n.tone(t));
  return dark
    ? {
        "surface-dim": tone(6),
        "surface-bright": tone(24),
        "surface-container-lowest": tone(4),
        "surface-container-low": tone(10),
        "surface-container": tone(12),
        "surface-container-high": tone(17),
        "surface-container-highest": tone(22),
      }
    : {
        "surface-dim": tone(87),
        "surface-bright": tone(98),
        "surface-container-lowest": tone(100),
        "surface-container-low": tone(96),
        "surface-container": tone(94),
        "surface-container-high": tone(92),
        "surface-container-highest": tone(90),
      };
}

function block(scheme, palettes, dark) {
  const lines = [];
  for (const role of ROLES) {
    const argb = scheme[role];
    if (argb === undefined) continue;
    lines.push(`  --md-${kebab(role)}: ${hexFromArgb(argb)};`);
  }
  for (const [name, value] of Object.entries(surfaceContainers(palettes, dark))) {
    lines.push(`  --md-${name}: ${value};`);
  }
  return lines.join("\n");
}

const light = block(theme.schemes.light.toJSON(), theme.palettes, false);
const dark = block(theme.schemes.dark.toJSON(), theme.palettes, true);
const nav = Object.entries(NAV)
  .map(([k, v]) => `  --md-${k}: ${v};`)
  .join("\n");

// ASCII only in generated output: this file gets read by tools with varying
// encoding defaults, and a stray em-dash is not worth the ambiguity.
const css = `/* GENERATED by scripts/gen-theme.mjs - do not edit by hand.
 * Source colour: ${SOURCE}
 * Regenerate:    node --import ./scripts/register-loader.mjs scripts/gen-theme.mjs
 */

:root {
${light}

  /* Fixed brand chrome - a deliberate departure from stock M3, which would
     make the navigation drawer a light surface. */
${nav}
}

@media (prefers-color-scheme: dark) {
  :root {
${dark}
  }
}
`;

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "app", "theme.css");
writeFileSync(out, css, "utf8");
console.log(`wrote ${out}`);
console.log(`source ${SOURCE} -> primary ${hexFromArgb(theme.schemes.light.primary)}`);
