// GENERATED by scripts/gen-theme.mjs - do not edit by hand.
// Mirrors the ACCENTS list there, so the picker cannot drift from the CSS.

export type Accent = (typeof ACCENTS)[number]["id"];

export const ACCENTS = [
  { id: "purple", label: "Purple", seed: "#69559f" },
  { id: "teal", label: "Teal", seed: "#157069" },
  { id: "violet", label: "Violet", seed: "#8158f4" },
  { id: "amber", label: "Amber", seed: "#aa5413" },
  { id: "olive", label: "Olive", seed: "#3e5d17" },
  { id: "blue", label: "Blue", seed: "#0e80bb" },
  { id: "brown", label: "Brown", seed: "#76564B" },
] as const;

/** The one on bare `:root`, i.e. what renders with no data-accent set. */
export const DEFAULT_ACCENT: Accent = "purple";
